# Generated by Django 3.2.12 on 2022-05-22 18:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantecedente',
            fields=[
                ('cantecedente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True)),
                ('sinonimos', models.CharField(blank=True, max_length=1000, null=True)),
                ('triage', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'triage"."cantecedente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CconstanteVital',
            fields=[
                ('cconstante_vital_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True)),
                ('min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alerta_menor_que', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alerta_mayor_que', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'triage"."cconstante_vital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CespecialidadTipo',
            fields=[
                ('cespecialidad_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('agrupar_en_otras', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboards"."cespecialidad_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CestadoAlerta',
            fields=[
                ('cestado_alerta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'triage"."cestado_alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CestadoAlertaOpcion',
            fields=[
                ('cestado_alerta_opcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'triage"."cestado_alerta_opcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CestadoPaciente',
            fields=[
                ('cestado_paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dashboards"."cestado_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmoduloVista',
            fields=[
                ('cmodulo_vista_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('acciones', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'general"."cmodulo_vista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmotivoAlta',
            fields=[
                ('cmotivo_alta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dashboards"."cmotivo_alta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrecursoTipo',
            fields=[
                ('crecurso_tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_recurso', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dashboards"."crecurso_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CresultadoPrueba',
            fields=[
                ('cresultado_prueba_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dashboards"."cresultado_prueba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crol',
            fields=[
                ('crol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=45, null=True)),
                ('sudo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'general"."crol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Csintoma',
            fields=[
                ('csintoma_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=30, null=True)),
                ('principal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'triage"."csintoma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TcapacidadHospitalMedico',
            fields=[
                ('tcapacidad_hospital_medico_id', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidad', models.BooleanField(blank=True, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('thospital_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."tcapacidad_hospital_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TcapacidadHospitalRecurso',
            fields=[
                ('tcapacidad_hospital_recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('disponible', models.IntegerField(blank=True, null=True)),
                ('thospital_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."tcapacidad_hospital_recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TetlReporteHistorico',
            fields=[
                ('tetl_reporte_historico_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.TimeField(blank=True, null=True)),
                ('reporte', models.CharField(blank=True, max_length=50, null=True)),
                ('log', models.CharField(blank=True, max_length=26, null=True)),
                ('estatus', models.CharField(blank=True, max_length=10, null=True)),
                ('tusuario_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."tetl_reporte_historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThistoricoIngreso',
            fields=[
                ('thistorico_ingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('fecha_reingreso', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dashboards"."thistorico_ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thospital',
            fields=[
                ('thospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('atiende_covid19', models.BooleanField(blank=True, null=True)),
                ('clues', models.CharField(blank=True, max_length=45, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'general"."thospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tingreso',
            fields=[
                ('tingreso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nhc', models.IntegerField()),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=11000, null=True)),
                ('notas', models.CharField(blank=True, max_length=1000, null=True)),
                ('thospital_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."tingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TpacienteSami',
            fields=[
                ('tpaciente_sami_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio_alcaldia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dashboards"."tpaciente_sami',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TpacienteTriage',
            fields=[
                ('tpaciente_triage_id', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio_sintomas', models.DateField(blank=True, null=True)),
                ('embarazo', models.SmallIntegerField(blank=True, null=True)),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True)),
                ('filiacion', models.CharField(blank=True, max_length=100, null=True)),
                ('puntaje_news2', models.IntegerField(blank=True, null=True)),
                ('puntaje_qsofa', models.IntegerField(blank=True, null=True)),
                ('puntaje_glassgow', models.IntegerField(blank=True, null=True)),
                ('sospecha_covid', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'general"."tpaciente_triage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TpermisoRolVista',
            fields=[
                ('tpermiso_rol_vista_id', models.AutoField(primary_key=True, serialize=False)),
                ('acciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'general"."tpermiso_rol_vista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrecursoRegistro',
            fields=[
                ('trecurso_registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_fecha', models.TimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('tusuario_id', models.IntegerField()),
                ('thospital_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."trecurso_registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TregistroConstanteVital',
            fields=[
                ('tpaciente_triage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'triage"."tregistro_constante_vital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TregistroEstadoAlerta',
            fields=[
                ('tpaciente_triage_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'triage"."tregistro_estado_alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TregistroPaciente',
            fields=[
                ('tregistro_paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.TimeField(blank=True, null=True)),
                ('tusuario_id', models.IntegerField()),
                ('thospital_id', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards"."tregistro_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tusuario',
            fields=[
                ('tusuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.SmallIntegerField()),
                ('fecha_creado', models.TimeField(default=django.utils.timezone.now)),
                ('fecha_inhabilitado', models.TimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('contrasena', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'general"."tusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TregistroAntecedente',
            fields=[
                ('cantecedente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.cantecedente')),
                ('tpaciente_triage_id', models.IntegerField()),
            ],
            options={
                'db_table': 'triage"."tregistro_antecedente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TregistroSintoma',
            fields=[
                ('csintoma', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.csintoma')),
                ('tpaciente_triage_id', models.IntegerField()),
            ],
            options={
                'db_table': 'triage"."tregistro_sintoma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tusuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inhabilitado', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(blank=True, max_length=500, null=True)),
                ('crol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.crol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('thospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.thospital')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'public"."usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
