# Generated by Django 3.2.12 on 2022-05-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tusuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
